[build] 
  image = "n8nio/n8n:latest" 
[env] 
  N8N_HOST = "n8n-hafez.fly.dev" 
  WEBHOOK_URL = "https://n8n-hafez.fly.dev" 
[[services]] 
  internal_port = 5678 
  protocol = "tcp" 
[[services.ports]] 
  port = 80 
  handlers = ["http"] 
[[services.ports]] 
  port = 443 
  handlers = ["tls","http"] 
