app = "n8n-hafez"
primary_region = "ams"

[env]
  N8N_BASIC_AUTH_ACTIVE = "true"
  N8N_BASIC_AUTH_USER = "admin"
  N8N_BASIC_AUTH_PASSWORD = "yourStrongPassword123!"
  N8N_HOST = "0.0.0.0"
  N8N_PORT = "5678"
  WEBHOOK_URL = "https://n8n-hafez.fly.dev/"
  GENERIC_TIMEZONE = "Africa/Cairo"
  N8N_PROTOCOL = "http"

[[services]]
  internal_port = 5678
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.tcp_checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "10s"
